[package]
entrypoint = "lib.typ"
name = "codepoint"
version = "0.1.0"
authors = ["Clarissa Milligan, Reese Hatfield"]
license = "MIT"
description = "Utilities for creating programming labs and exams"
